const assert = require('assert');
const fs = require('fs');
const path = require('path');

(() => {
  const root = path.join(__dirname, '..');
  const read = (...parts) => fs.readFileSync(path.join(root, ...parts), 'utf8');
  const moduleCode = read('assets', 'js', 'dashboard', 'live-classes.js');
  const schedule = read('supabase', 'functions', 'schedule-live-class', 'index.ts');
  const join = read('supabase', 'functions', 'join-live-class', 'index.ts');
  const options = read('supabase', 'functions', 'live-class-options', 'index.ts');
  const migration = read('supabase', 'migrations', '202608100005_upgrade_live_classes_google_meet.sql');
  const classAndTeacherMigration = read('supabase', 'migrations', '202608110004_seed_standard_classes_and_teacher_ids.sql');
  const attendanceMigration = read('supabase', 'migrations', '202609010002_add_live_class_attendance_columns.sql');

  assert.ok(schedule.includes('oauth2.googleapis.com/token'), 'scheduling must exchange a server-side refresh token');
  assert.ok(schedule.includes('token?.error_description'), 'scheduling must return Google OAuth failure details safely');
  assert.ok(schedule.includes('conferenceDataVersion=1'), 'scheduling must request a Google Meet conference');
  assert.ok(schedule.includes('teacher_subjects'), 'server must verify teacher assignment');
  assert.ok(join.includes('student_can_access_live_class'), 'server must verify student enrollment before returning a link');
  assert.ok(join.includes('live_class_students'), 'server must verify explicit class approval before returning a link');
  assert.ok(join.includes('recordStudentAttendanceOnJoin'), 'joining a live class should automatically trigger attendance capture for students');
  assert.ok(join.includes('.from("attendance")'), 'join endpoint must write to attendance when a student joins');
  assert.ok(join.includes('live_class_id,student_id'), 'attendance recording should be idempotent per class join');
  assert.ok(join.includes('hasUniversalLiveClassAccess'), 'administrators must be allowed to join every active live class');
  assert.ok(schedule.includes('approved_student_ids'), 'scheduling must persist the teacher-approved student roster');
  assert.ok(options.includes('teacher_subjects'), 'scheduling options must be scoped to the authenticated teacher');
  assert.ok(options.includes('select("teacher_id,subject_id,class_id")'), 'scheduling options must return the teacher ID used by the portal assignment filter');
  assert.ok(!options.includes('student_subjects'), 'scheduling options must not depend on student subject enrolments');
  assert.ok(options.includes('const students = studentsResult.data || []'), 'scheduling options must return every student in an assigned class');
  assert.ok(moduleCode.includes('approved_student_ids'), 'teacher form must submit approved students');
  assert.ok(moduleCode.includes('await API.functionErrorMessage'), 'the scheduling form must display the Edge Function error body');
  assert.ok(moduleCode.includes('agora-create-room'), 'teacher hosts must request a dedicated room creation token');
  assert.ok(moduleCode.includes('agora-join-room'), 'students must request a dedicated room join token');
  assert.ok(!moduleCode.includes('AGORA_TOKEN'), 'the browser must not depend on a static Agora token field');
  assert.ok(read('supabase', 'functions', 'agora-create-room', 'index.ts').includes('Only teachers and administrators can create an Agora room'), 'teacher-only creation route must reject non-teachers');
  assert.ok(read('supabase', 'functions', 'agora-join-room', 'index.ts').includes('live_class_students'), 'student-only join route must verify approval before plane access');
  assert.ok(migration.includes("public.current_user_role() in ('ceo', 'admin', 'executive')"), 'administrators must be able to see every live class in the portal');
  assert.ok(moduleCode.includes('String(label.dataset.classId) === classId'), 'student picker must filter by the selected class');
  assert.ok(!moduleCode.includes('enrolledSubjects.includes(subjectId)'), 'student picker must not filter learners by subject enrolment');
  assert.ok(schedule.includes('.eq("class_id", classId)'), 'schedule endpoint must reject students outside the selected class');
  assert.ok(!schedule.includes('subjectEnrollments'), 'schedule endpoint must not reject class students who lack subject enrolment');
  assert.ok(join.includes('id,class_id,subject_id'), 'join authorization must load the live class class_id');
  assert.ok(moduleCode.includes('join-live-class'), 'browser must use the protected join endpoint');
  assert.ok(!moduleCode.includes('meet.jit.si'), 'Jitsi room generation must not remain');
  assert.ok(migration.includes('get_live_classes'), 'database must expose an enrollment-scoped class listing');
  assert.ok(classAndTeacherMigration.includes("'Primary 3'"), 'standard class options must be seeded for class selectors');
  assert.ok(classAndTeacherMigration.includes("'SSS 3'"), 'senior class options must be seeded for class selectors');
  assert.ok(classAndTeacherMigration.includes('teacher_employee_id'), 'live classes must return the generated teacher employee ID');
  assert.ok(attendanceMigration.includes('add column if not exists subject_id'), 'attendance schema must support subject-aware live class attendance');
  assert.ok(attendanceMigration.includes('attendance_live_class_student_unique'), 'attendance schema must prevent duplicate attendance rows for the same student join');
  assert.ok(moduleCode.includes('teacher_employee_id'), 'live class cards must display the generated teacher employee ID');
  assert.ok(moduleCode.includes('data-live-action="start"'), 'teachers should be able to start their own scheduled classes');
  assert.ok(moduleCode.includes('action === "start" ? "live"'), 'starting a class should persist live status');
  assert.ok(moduleCode.includes('toISOString()'), 'the browser should send scheduled times with an explicit timezone');
  assert.ok(read('supabase', 'functions', '_shared', 'live-class.ts').includes('if (status === "live") return "live"'), 'the join function should honor a manually started class');
  assert.ok(read('supabase', 'migrations', '202608110005_fix_admission_and_live_class_statuses.sql').includes("when lc.status = 'live' then 'live'"), 'the live class query should preserve a manually started state');
  const teacherStudentMigration = read('supabase', 'migrations', '202608190011_match_teacher_students_by_assigned_class.sql');
  assert.ok(!teacherStudentMigration.includes('student_subjects'), 'teacher student visibility must not depend on student subject enrolment');
  assert.ok(teacherStudentMigration.includes('ts.class_id = s.class_id'), 'teacher student visibility must depend on matching classes');
  console.log('live classes Google Meet regression test passed');
})();
