const assert = require('assert');
const fs = require('fs');
const path = require('path');

(() => {
  const root = path.join(__dirname, '..');
  const read = (...parts) => fs.readFileSync(path.join(root, ...parts), 'utf8');
  const moduleCode = read('assets', 'js', 'dashboard', 'live-classes.js');
  const config = read('assets', 'js', 'config.js');
  const schedule = read('supabase', 'functions', 'schedule-live-class', 'index.ts');
  const join = read('supabase', 'functions', 'join-live-class', 'index.ts');
  const options = read('supabase', 'functions', 'live-class-options', 'index.ts');
  const migration = read('supabase', 'migrations', '202609100001_finalize_agora_live_classes.sql');
  const classAndTeacherMigration = read('supabase', 'migrations', '202608110004_seed_standard_classes_and_teacher_ids.sql');
  const attendanceMigration = read('supabase', 'migrations', '202609010002_add_live_class_attendance_columns.sql');

  assert.ok(schedule.includes('makeAgoraRoomName'), 'scheduling must create a server-side Agora channel name');
  assert.match(config, /APP_ID:\s*"[a-f0-9]{32}"/i, 'the browser must have a valid public Agora App ID');
  assert.ok(schedule.includes('meeting_url: roomUrl'), 'scheduling must store the Agora room URL in the live class record');
  assert.ok(!schedule.includes('oauth2.googleapis.com/token'), 'scheduling must no longer rely on Google Calendar OAuth');
  assert.ok(schedule.includes('teacher_subjects'), 'server must verify teacher assignment');
  assert.ok(schedule.includes('assignmentError'), 'schedule endpoint must surface teacher-assignment lookup failures');
  assert.ok(join.includes('student_can_access_live_class'), 'server must verify student enrollment before returning a link');
  assert.ok(join.includes('live_class_students'), 'server must verify explicit class approval before returning a link');
  assert.ok(join.includes('recordStudentAttendanceOnJoin'), 'joining a live class should automatically trigger attendance capture for students');
  assert.ok(join.includes('.from("attendance")'), 'join endpoint must write to attendance when a student joins');
  assert.ok(join.includes('live_class_id,student_id'), 'attendance recording should be idempotent per class join');
  assert.ok(join.includes('hasUniversalLiveClassAccess'), 'administrators must be allowed to join every active live class');
  assert.ok(schedule.includes('approved_student_ids'), 'scheduling must accept the teacher-selected roster');
  assert.ok(schedule.includes('.in("id", approvedStudentIds)'), 'scheduling must validate every selected student against the selected class');
  assert.ok(schedule.includes('notificationRows'), 'scheduling must notify every selected student');
  assert.ok(options.includes('teacher_subjects'), 'scheduling options must be scoped to the authenticated teacher');
  assert.ok(options.includes('select("teacher_id,subject_id,class_id")'), 'scheduling options must return the teacher ID used by the portal assignment filter');
  assert.ok(!options.includes('student_subjects'), 'scheduling options must not depend on student subject enrolments');
  assert.ok(options.includes('const students = studentsResult.data || []'), 'scheduling options must return every student in an assigned class');
  assert.ok(moduleCode.includes('approved_student_ids'), 'teacher form must submit manually selected students');
  assert.ok(moduleCode.includes('data-select-all-students'), 'teacher form must support selecting the full class roster');
  assert.ok(moduleCode.includes('showLiveClassNotifications'), 'students must receive an in-app live-class popup');
  assert.ok(moduleCode.includes('await API.functionErrorMessage'), 'the scheduling form must display the Edge Function error body');
  assert.ok(moduleCode.includes('agora-create-room'), 'teacher hosts must request a dedicated room creation token');
  assert.ok(moduleCode.includes('agora-join-room'), 'students must request a dedicated room join token');
  assert.ok(moduleCode.includes('const canPublish = isTeacherHost || this.role() === "student"'), 'approved students must be able to publish their own classroom audio and video');
  assert.ok(moduleCode.includes('tokenResponse.role === "publisher"'), 'the browser must publish tracks only when the server grants publisher access');
  assert.ok(moduleCode.includes('createMicrophoneAndCameraTracks'), 'the host must create Agora-owned local audio and video tracks together');
  assert.ok(moduleCode.includes('await client.publish(localAudioTrack)'), 'the host must publish only its local audio track');
  assert.ok(moduleCode.includes('await client.publish(localVideoTrack)'), 'the host must publish only its local video track');
  assert.ok(moduleCode.includes('const storedChannel = String(session?.agora_channel_name || "").trim()'), 'the browser must preserve the server-stored Agora channel exactly');
  assert.ok(moduleCode.includes('static agoraUid(session)'), 'the browser must derive a safe 32-bit Agora UID instead of converting a UUID to an unsafe number');
  assert.ok(moduleCode.includes('globalThis.crypto?.randomUUID?.()'), 'Agora UIDs must be unique for each participant connection and reconnect');
  assert.ok(moduleCode.includes('const source = `${sessionId}:${userId}:${nonce}`'), 'Agora UIDs must combine the session, participant, and connection nonce');
  assert.ok(moduleCode.includes('AgoraRTC_N-4.24.8.js'), 'the browser must use a current pinned Agora Web SDK');
  assert.ok(moduleCode.includes('AgoraRTC_N-production.js'), 'fallback CDNs must use the package’s actual browser-bundle filename');
  assert.ok(moduleCode.includes('cdn.jsdelivr.net/npm/agora-rtc-sdk-ng'), 'the browser must retry a second fallback CDN when Agora CDN is unavailable');
  assert.ok(!moduleCode.includes('AGORA_TOKEN'), 'the browser must not depend on a static Agora token field');
  assert.ok(read('supabase', 'functions', 'agora-create-room', 'index.ts').includes('Only teachers and administrators can create an Agora room'), 'teacher-only creation route must reject non-teachers');
  assert.ok(read('supabase', 'functions', 'agora-join-room', 'index.ts').includes('live_class_students'), 'student-only join route must verify approval before plane access');
  assert.ok(read('supabase', 'functions', 'agora-join-room', 'index.ts').includes('role === "student" ? RtcRole.PUBLISHER'), 'approved students must receive publisher access for two-way live classes');
  for (const endpoint of ['agora-create-room', 'agora-join-room', 'agora-room', 'agora-token']) {
    const endpointCode = read('supabase', 'functions', endpoint, 'index.ts');
    assert.ok(endpointCode.includes('statusFor('), `${endpoint} must refuse tokens outside the live session window`);
    assert.ok(endpointCode.includes('Invalid Agora channel for this live class.'), `${endpoint} must bind tokens to the stored class channel`);
  }
  assert.ok(migration.includes("public.current_user_role() in ('ceo', 'admin', 'executive')"), 'administrators must be able to see every live class in the portal');
  assert.ok(!moduleCode.includes('enrolledSubjects.includes(subjectId)'), 'live classes must not depend on subject enrolment');
  assert.ok(schedule.includes('.eq("class_id", classId)'), 'schedule endpoint must validate selected students only against the selected class');
  assert.ok(!schedule.includes('subjectEnrollments'), 'schedule endpoint must not reject class students who lack subject enrolment');
  assert.ok(join.includes('id,class_id,subject_id'), 'join authorization must load the live class class_id');
  assert.ok(moduleCode.includes('join-live-class'), 'browser must use the protected join endpoint');
  assert.ok(!moduleCode.includes('meet.jit.si'), 'Jitsi room generation must not remain');
  assert.ok(migration.includes('agora_channel_name'), 'database must persist the Agora channel identity');
  assert.ok(classAndTeacherMigration.includes("'Primary 3'"), 'standard class options must be seeded for class selectors');
  assert.ok(classAndTeacherMigration.includes("'SSS 3'"), 'senior class options must be seeded for class selectors');
  assert.ok(classAndTeacherMigration.includes('teacher_employee_id'), 'live classes must return the generated teacher employee ID');
  assert.ok(attendanceMigration.includes('add column if not exists subject_id'), 'attendance schema must support subject-aware live class attendance');
  assert.ok(attendanceMigration.includes('attendance_live_class_student_unique'), 'attendance schema must prevent duplicate attendance rows for the same student join');
  assert.ok(moduleCode.includes('teacher_employee_id'), 'live class cards must display the generated teacher employee ID');
  assert.ok(moduleCode.includes('data-live-action="start"'), 'teachers should be able to start their own scheduled classes');
  assert.ok(moduleCode.includes('data-schedule-submit'), 'schedule form must prevent duplicate submissions while a request is in flight');
  assert.ok(moduleCode.includes('End time must be after the start time.'), 'schedule form must validate the session time range before requesting the server');
  assert.ok(moduleCode.includes('action === "start" ? "live"'), 'starting a class should persist live status');
  assert.ok(moduleCode.includes('data-end-agora'), 'teachers should be able to end a class from the full-page classroom');
  assert.ok(moduleCode.includes('data-agora-preview-resize'), 'publishers should be able to manually resize their camera preview');
  assert.ok(moduleCode.includes('data-toggle-camera-fill'), 'publishers should be able to expand their camera preview to fill the video stage');
  assert.ok(moduleCode.includes('data-toggle-agora-sidebar'), 'class details and chat should start in a collapsible sidebar');
  assert.ok(moduleCode.includes('createDataStream'), 'class chat comments should be delivered through Agora data streams');
  assert.ok(moduleCode.includes('sendStreamMessage'), 'participants should be able to send class chat comments');
  assert.ok(moduleCode.includes('createScreenVideoTrack'), 'teachers and approved students should be able to share their screen');
  assert.ok(moduleCode.includes('toISOString()'), 'the browser should send scheduled times with an explicit timezone');
  assert.ok(read('supabase', 'functions', '_shared', 'live-class.ts').includes('if (status === "live") return "live"'), 'the join function should honor a manually started class');
  assert.ok(read('supabase', 'migrations', '202608110005_fix_admission_and_live_class_statuses.sql').includes("when lc.status = 'live' then 'live'"), 'the live class query should preserve a manually started state');
  const teacherStudentMigration = read('supabase', 'migrations', '202608190011_match_teacher_students_by_assigned_class.sql');
  assert.ok(!teacherStudentMigration.includes('student_subjects'), 'teacher student visibility must not depend on student subject enrolment');
  assert.ok(teacherStudentMigration.includes('ts.class_id = s.class_id'), 'teacher student visibility must depend on matching classes');
  console.log('live classes Agora regression test passed');
})();
