-- Track notification read state per profile so unread badges sync across devices.
create table if not exists public.notification_reads (
    id bigint generated by default as identity primary key,
    notification_id uuid not null references public.notifications(id) on delete cascade,
    profile_id uuid not null references public.profiles(id) on delete cascade,
    read_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (notification_id, profile_id)
);

create index if not exists notification_reads_profile_id_idx
    on public.notification_reads(profile_id);

create index if not exists notification_reads_notification_id_idx
    on public.notification_reads(notification_id);

create index if not exists notification_reads_read_at_idx
    on public.notification_reads(read_at desc);

alter table public.notification_reads enable row level security;

drop policy if exists notification_reads_select_own on public.notification_reads;
create policy notification_reads_select_own
    on public.notification_reads
    for select
    to authenticated
    using (profile_id = auth.uid());

drop policy if exists notification_reads_insert_own on public.notification_reads;
create policy notification_reads_insert_own
    on public.notification_reads
    for insert
    to authenticated
    with check (profile_id = auth.uid());

drop policy if exists notification_reads_update_own on public.notification_reads;
create policy notification_reads_update_own
    on public.notification_reads
    for update
    to authenticated
    using (profile_id = auth.uid())
    with check (profile_id = auth.uid());
